language: android
dist: trusty

android:
  components:
  - tools # to update the repository XML files
  - tools # to update the SDK tools themselves

  - platform-tools
  - build-tools-28.0.3
  - android-28

  - extra

jdk:
  - oraclejdk8
